### PR TITLE
Auto disable colored output for unsupported Windows shells

### LINKED ISSUE #129: Colored output does not work on cmd.exe (Windows)
Need another colorizer for Windows.

### PR DESCRIPTION
**Pull request by iology**
Resolves #129

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you very much for working on this!

I recently found this: https://github.com/ogham/rust-ansi-term/blob/090e0a383d73a43e2f80a7b466e8feeee97c4c76/src/windows.rs#L10

Do you think we could utilize this instead of pulling in all this OS-dependent code?

**Comment by iology** [comment]
Oh yeah, very good. 😄 Rebased and tested on Win7 & Win10.

**Comment by iology** [comment]
Oops, failed. Filed an issue to the upstream: https://github.com/ogham/rust-ansi-term/issues/31

**Comment by iology** [comment]
The previous successful patch is here: https://github.com/jakwings/fd/commit/a44e6775ba4938bc1ecbe3735101a9a50474e740

**Comment by iology** [comment]
While `ansi-term::enable_ansi_support` may take times to stabilize, I move jakwings/fd@a44e677 into a crate in the subdirectory "win", thus slightly reducing the OS macros used.

**Comment by sharkdp** [comment]
Great, thank you very much!

Let's keep an eye on https://github.com/ogham/rust-ansi-term/issues/31

**Pull request merged**
