### PR TITLE
CI experiment

### PR DESCRIPTION
**Pull request by sharkdp**
Just a small experiment - I'm not going to merge this.

### CODE REVIEW

**Comment by sharkdp** [comment]
Ok, so it seems like the `unsafe` block was (somehow) causing the CI failures in both #136 (on `x86_64-pc-windows-msvc`) and #142 (on `i686-unknown-linux-musl`).

Patching the `unsafe` block fixes the tests in both cases.

/CC @DTibbs @iology @mmstick

**Comment by mmstick** [comment]
Is a bit wasteful to make a second copy of the command template for the sake of wrapping it in an Arc. I wonder why that was failing there.

**Comment by sharkdp** [comment]
Closing in favor of #152

**Comment by Detegr** [comment]
> I wonder why that was failing there.

[The documentation](https://doc.rust-lang.org/stable/std/sync/struct.Arc.html#method.from_raw) states that `The raw pointer must have been previously returned by a call to a Arc::into_raw` which was not the case here.

**Pull request closed without merging**
