### PR TITLE
Adding --perm option to filter by Unix 3 digits numeric permission notation

### PR DESCRIPTION
**Pull request by eduriol**
- Added --perm option for Unix systems accepting a 3 digit number to filter by Unix permission system. Example: 'fd --perm 755' will yield only results with 755 permission level enabled.
- I took mainly the implementation of the --size option as inspiration for the implementation of this one.
- Added unitary and integration tests to cover this new option.

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you very much for your contribution!

Maybe we should first discuss this in a more general sense in the corresponding feature request ticket: #523. I will comment there.

**Comment by eduriol** [comment]
I'm trying to figure out how to overcome the problem of this solution not compiling in Windows platforms.

**Comment by eduriol** [comment]
Ok, I'm having a hard time making it compiling in Windows platform to pass the CI tests, but you are right, let's discuss it at high level first.

**Comment by sharkdp** [comment]
closing for now (cleaning up list of open PRs).

**Pull request closed without merging**
