### PR TITLE
ci: Support large page sizes on AArch64

### LINKED ISSUE #1085: Binary releases of fd crash on Asahi Linux because of jemalloc using 8kb page sizes
Binary releases crash because they don't support 16kb-aligned pages.

I get the following error with the latest binary releases (both from github releases, and the Arch Linux ARM repos):
```
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
memory allocation of 5 bytes failed
[1]    28699 IOT instruction (core dumped)  ./fd-v8.4.0-aarch64-unknown-linux-gnu/fd
```

Building from source fixes the issue (apparently jemalloc has internal logic to detect page size?)

M1 Macs use 16KB pages by default [at a hardware level](https://github.com/AsahiLinux/docs/wiki/Broken-Software#why-not-just-use-4k-pages-then), so this is a common problem with [Ashai Linux](https://github.com/tikv/jemallocator). 

There are two simple fixes that occur to me:
1. disabling jemalloc for AArch64 Linux
2. Compiling jemalloc to use 64K pages (which will work anywhere). This is what the [ALARM Rust](https://github.com/archlinuxarm/PKGBUILDs/commit/19a1393) package does.

The second one will probably have to be filled in the upstream [jemallactor](https://github.com/tikv/jemallocator) project (in fact that could be a more appropriate to file this issue....)

### PR DESCRIPTION
**Pull request by tavianator**
Fixes #1085.

### CODE REVIEW

**Comment by tmccombs** [comment]
Will this break any aarch64 systems? Or will it just use more memory?

**Comment by tavianator** [comment]
I don't think it will break any systems, but I'll test it on mine just to be sure.  I don't have one with large pages though so I can't even validate the fix

**Review by tmccombs — APPROVED** [review]

**Comment by mathomp4** [comment]
> I don't think it will break any systems, but I'll test it on mine just to be sure. I don't have one with large pages though so I can't even validate the fix

Well, once it's in a release, I can test it. 

Or I guess I can do the `cargo` route! How would someone who's never used `cargo` outside of a tutorial get and test this? 😄

**Comment by tavianator** [comment]
I think just

```console
$ JEMALLOC_SYS_WITH_LG_PAGE=16 cargo install fd-find
```

should work

**Comment by tmccombs** [comment]
I'll try to put together a release tonight

**Comment by mathomp4** [comment]
Sadly, this did not seem to fix it on my NVIDIA GraceGrace node. Let me try a cargo build...

**Comment by tavianator** [comment]
@mathomp4 Oh, that's my mistake, I didn't realize the cross build uses docker.  I made https://github.com/sharkdp/fd/pull/1549 which should fix it for real.

**Pull request merged**
