### PR TITLE
Added detail on parallel execution job pool to man page and README.

### PR DESCRIPTION
**Pull request by detly**
Proposed for #450 .

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you very much for your contribution.

The man page is usually kept in sync with the `--help` text of `fd`. The `--help` text acually already mentions it:
```
    -j, --threads <num>
            Set number of threads to use for searching & executing
            (default: number of available CPU cores)
```

Also, I think we should probably not use the word "job pool". I'm not sure if all users will be familiar with the term.

**Comment by detly** [comment]
Yep, that works too. I totally missed it.

**Comment by detly** [comment]
Redid it so the wording is consistent between the help text and man page.

**Comment by sharkdp** [comment]
Thank you very much!

**Pull request merged**
