### PR TITLE
Update some dependencies

### PR DESCRIPTION
**Pull request by tmccombs**
Combination of dependabot prs.

### CODE REVIEW

**Comment by sharkdp** [comment]
> Combination of dependabot prs.

Do you think the dependabot PRs are useless? (honest opinion please)
I realize they can be a bit annoying and maybe spam our notification inboxes, but I like that we can easily see the changelog for each of the dependencies (I usually read it to see if there are important notes or breaking changes that would not show up as a compilation error) and also the individual build status.

**Review by sharkdp — APPROVED** [review]

**Comment by tavianator** [comment]
I actually don't mind the dependabot PRs, but I also like these "rollups."  I don't think it's necessary to keep separate commits around for bumping the version of each dependency.  Not a strong opinion though.

**Comment by tmccombs** [comment]
I don't have a strong opinion either way.

**Comment by sharkdp** [comment]
Ok, thank you. Since the dependabot PRs auto-close, I think the current workflow with both the individual PRs and the "rollup" is also fine.

**Pull request merged**
