### PR TITLE
Format the source code using `rustfmt`

### PR DESCRIPTION
**Pull request by Detegr**
Just a `rustfmt` pass in this PR. I'll do Travis setup separately. #99

### CODE REVIEW

**Comment by sharkdp** [comment]
Looks good, thank you very much!

I would like to give #95 and #98 a chance to be merged first before we proceed, as this will likely introduces a lot of merge conflicts.

**Comment by Detegr** [comment]
Sure, let's merge pending PR's out of the way and I'll rebase this then.

**Comment by sharkdp** [comment]
Ok, if you could rebase this now (or reformat the current code), that would be great!

**Comment by sharkdp** [comment]
Thanks!

**Pull request merged**
