### PR TITLE
Refactoring main.rs : remove unused variable (empty_pattern)

### PR DESCRIPTION
**Pull request by LoveTube**
I think this PR is  just small code improvement , so I'd go ahead and open a PR, hope you don't mind. 
In main.rs, empty_pattern is used as a default value for pattern.
I think it's better remove empty_pattern and add "" for default pattern. Because it's more clear.

### CODE REVIEW

**Comment by sharkdp** [comment]
@LoveTube Welcome and Thank you for your contribution!

I believe this was needed in some older version of Rust (although not sure). Great that we can write this in a clearer way now.

**Comment by LoveTube** [comment]
OK. That's why this code is exist. I close this PR. Thanks

**Comment by sharkdp** [comment]
Sorry, I was unclear: I think we should integrate this now (because we have bumped the minimum required Rust version from 1.16 to 1.19 recently).

**Comment by LoveTube** [comment]
@sharkdp I just read your comment, I think you're right.

**Comment by sharkdp** [comment]
Thanks,

**Pull request merged**
