### PR TITLE
Add Examples to README redux

### PR DESCRIPTION
**Pull request by deg4uss3r**

### CODE REVIEW

**Comment by sharkdp** [comment]
Sorry to be a pain, but now there is still an unrelated change in the README file that should not be included when merging this. Thanks for your patience.

**Comment by deg4uss3r** [comment]
No problem, new commit fixes that weird issues, it must have been a new line/carrage return issue?

**Comment by sharkdp** [comment]
I have thought about this a bit more, and I would like to change a few of the examples (after merging this). In particular, I would like to try to find real-world scenarios for most of the examples (as compared to searches in a demo environment).

If you are still interested in helping, you are more than welcome. In any case, thank you very much!!

**Comment by deg4uss3r** [comment]
@sharkdp No problem! I think the piping to `xargs` is a great example, I did just today in fact. I'll keep my eye out for the real world uses I use fd for :) Thank you for the introduction, I'm also looking forward to writing some rust code for it too ;)

**Pull request merged**
