### PR TITLE
Fix path check (fixes #113)

### PR DESCRIPTION
**Pull request by iology**

### CODE REVIEW

**Comment by iology** [comment]
Not ready to merge. Wait.

**Comment by iology** [comment]
Still not ready to merge.

**Comment by iology** [comment]
Ok, please review. ;-)

**Comment by iology** [comment]
About Path::is_dir(".") see: https://github.com/rust-lang/rust/issues/45302

**Comment by iology** [comment]
I have done some refactoring, so that `base_dir` is no longer needed. Also fixed a bug about symlink on Windows during the refactoring.

**Comment by sharkdp** [comment]
This is really great! So much cleaner now. Thank you very much.

**Pull request merged**
