### PR TITLE
Update man page

### LINKED ISSUE #408: Man page doesn't explain search patterns
The man page doesn't say what form search patterns should take. The README here on GitHub says they are regular expressions, but not what kind of REs (I guess they are not PCREs, because there's an issue for adding that).

Suggestion: document in man page that the pattern argument is a regular expression, and say what kind of regular expression ops are supported.

### PR DESCRIPTION
**Pull request by rootbid**
man page updated for explaining search patterns.
- [x] Add syntax patterns for RE.
- [x] Add examples with RE syntax.

This commit resolves #408

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you very much for your contribution!

It will probably take a few days until I find the time to review it.

**Comment by sharkdp** [comment]
To be honest, I'm not sure we should "clutter" the man page with a full description of regular expression syntax. I'd rather just refer to https://docs.rs/regex/#syntax which includes an up-to-date description of the supported syntax.

**Comment by rootbid** [comment]
I do agree as this would mean updating the syntax on the man page as per original revisions.
So, do you think a link directing to the supported syntax on the man page would suffice?

**Comment by rootbid** [comment]
I hope this does it.

**Comment by sharkdp** [comment]
Thank you very much

**Pull request merged**
