### PR TITLE
Small screencast updates

### PR DESCRIPTION
**Pull request by sharkdp**

### CODE REVIEW

**Comment by sharkdp** [comment]
@marionebl I updated a few things in the screencast and everything worked just fine locally. After uploading to GitHub in this PR, the SVG size is much too small (the file works just fine when downloaded). 

Do you know if this could be related to https://github.com/marionebl/svg-term-cli/issues/5 ?

**Comment by marionebl** [comment]
This is odd. 

What dimension (columns x rows) had the terminal session you executed `svg-term --command="bash doc/screencast.sh" --out doc/screencast.svg --padding=10` in?

**Comment by sharkdp** [comment]
```
▶ tput cols
64

▶ tput lines
19
```

**Comment by marionebl** [comment]
Ok, found the issue. I removed the explicit `width` and `height` attributes on the toplevel `svg` at some point:

```
<svg width="660" height="432.49" ...
```

does the trick

Will publish a fix for this within the next hour.

**Comment by sharkdp** [comment]
Ah - indeed. Thank you very much!

**Comment by marionebl** [comment]
Published the relevant fix via `svg-term@1.1.6`. Reinstalling `svg-term-cli` should pull in the latest version.

**Comment by sharkdp** [comment]
> Published the relevant fix via svg-term@1.1.6. Reinstalling svg-term-cli should pull in the latest version.

Great, thank you!

**Pull request merged**
