### PR TITLE
Adding integration test for -x/--exec

### PR DESCRIPTION
**Pull request by DTibbs**
Added some testing of --exec command for Issue #134

### CODE REVIEW

**Comment by DTibbs** [comment]
Interesting AppVeyor failed on `x86_64-pc-windows-msvc` as that was the platform and toolchain I tested it locally on. Looks like a powershell path separator issue? I tested in cmd.exe.

**Comment by DTibbs** [comment]
Now I'm just guessing what AppVeyor's issue is. I don't get the same result testing locally in powershell w/ same version of cargo/rustc/etc.
Going to try and escape the string after `--exec` to see if that fixes it, as the following looks like it _might_ be the problem:
```	thread 'test_exec' panicked at '`fd --exec echo found foo` did not exit successfully.```

**Comment by DTibbs** [comment]
Looks like the test on AppVeyor for `x86_64-pc-windows-msvc` is returning error code C0000374. 
No idea what's causing that. As evident in the log, there is nothing on stderr.
This one is a stumper. Something about how the processes are being spawned that powershell x64 doesn't like?
Last try is to specify `cmd` in the appveyor.yml. Not sure if that's desired. I do not use, and haven't seen a lot of powershell use, when developing in Rust on Windows, so maybe it's not that big of a deal to use `cmd` on AppVeyor.

**Comment by sharkdp** [comment]
Welcome and thank you very much for working on this!

#135 has been fixed in the meantime. I haven't looked at the CI failures here, but maybe this could help.

**Comment by sharkdp** [comment]
See #142 by @iology for some progress on this.

**Comment by sharkdp** [comment]
I'm closing this in favor of #142. Thank you very much for your help!

**Pull request closed without merging**
