### PR TITLE
Added example for searching exactly a filename

### PR DESCRIPTION
**Pull request by joseph62**
Hello,

This PR is meant to address issue #692.

Let me know if any tweaks would make the example more clear. :)

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you for your contribution.

It would be great if we could find a more realistic example where the file is not directly located in the search folder. And where the filename contains a file-extension. This makes the glob option interesting, as the `.` would be e special character in a regex. Maybe:
```
fd -g httpd.conf
```

**Comment by joseph62** [comment]
That is a good point about the lack of realism in the example I used. I was trying to find one that hit these points:

1. The desired filename is a subset of other available filenames
2. The example is reproducible on the user's own machine

I wanted the example's output to be different than what a user might see if they drop the `-g` flag. The output of `fd sh` would include shell executables like `bash` and `ksh`.

Looking at this on my laptop now instead of my WSL installation I'm seeing an example that potentially hits both the criteria that I used as well as your points. 

```bash
$ cd /etc
$ fd -g console.perms
security/console.perms
$ fd console.perms # what it looks like without -g on my laptop
security/console.perms
security/console.perms.d
```

I did look at the proposed `fd httpd.conf` example on my machine and found that the results were the same with and without the `-g` flag. 

Let me know if this will work or if you have any other concerns.

**Comment by sharkdp** [comment]
Thank you for your comment. I agree with all points. Unfortunately, I can not reproduce your example on my machine. Another proposal:
```bash
▶ fd -g libc.so /usr
/usr/lib32/libc.so
/usr/lib/libc.so

 ▶ fd libc.so /usr   
/usr/lib32/libc.so
/usr/lib32/libc.so.6
/usr/lib/libc.so.6
/usr/lib/libc.so
```

But I'm also okay with your example.

**Comment by joseph62** [comment]
I love that! Applied.

**Review by sharkdp — APPROVED** [review]

**Comment by sharkdp** [comment]
thank you for the update!

**Pull request merged**
