### PR TITLE
Implement --type executable on Windows

### LINKED ISSUE #1051: -t executable flags can't show windows executable
### `-t executable` flags can't show windows executable 

图片

### PR DESCRIPTION
**Pull request by tavianator**
Fixes #1051.

### CODE REVIEW

**Comment by tavianator** [comment]
I don't know enough about Windows to actually make a test for this.  Might be nice if someone with Windows can confirm it works.

**Comment by sharkdp** [comment]
Thank you!

> I don't know enough about Windows to actually make a test for this.

We have the `fd.exe` available in the integration test suite, so maybe we could use that as a target for a simple test?

> Might be nice if someone with Windows can confirm it works.

/cc @xBLACKICEx

**Comment by xBLACKICEx** [comment]
> Thank you!
> 
> > I don't know enough about Windows to actually make a test for this.
> 
> We have the `fd.exe` available in the integration test suite, so maybe we could use that as a target for a simple test?
> 
> > Might be nice if someone with Windows can confirm it works.
> 
> /cc @xBLACKICEx

why not

**Review by tmccombs — APPROVED** [review]

**Review by sharkdp — APPROVED** [review]

**Comment by sharkdp** [comment]
Thank you!

**Pull request merged**
