### PR TITLE
Escape exec Inputs

### LINKED ISSUE #135: Path should be escaped when running '-x cmd'
This seems like a bug to me

``` bash
> touch 'file with spaces'

> fd -x 'ls "{}"'    # this is fine
file with spaces

> fd -x ls       
ls: cannot access 'file': No such file or directory
ls: cannot access 'with': No such file or directory
ls: cannot access 'spaces': No such file or directory
```

@mmstick - I'm mentioning you here just in case you are interested. I'm not trying to assign this to you.

### PR DESCRIPTION
**Pull request by mmstick**
Paths are now transformed using a state machine, which ensures that the final output is escaped when the inner value is returned. Nothing special beyond inputs now getting escaped.

Closes #135

### CODE REVIEW

**Comment by sharkdp** [comment]
Super, thank you very much!

**Comment by iology** [comment]
Other whitespace characters must also be escaped: TAB and LF

**Comment by iology** [comment]
Also there is another special chars in Windows shells: `^`

**Comment by mmstick** [comment]
Do tabs and such need to be escaped? I don't think it's possible to do that in a cross-shell manner. Bash, for example, would have to have it written like `$'path\twith\ttabs'`. In Ion, I've been thinking about adding an `$unescape('path\twith\ttabs')` method.

**Comment by mmstick** [comment]
Maybe if we just replace them with their corresponding ASCII sequences, and let the user handle them accordingly?

**Comment by iology** [comment]
The crate "shell-escape" just quotes the raw tabs/linefeeds/... in single-quoted strings. `$'...'` is also quoting. Anyway, the intermediate process is not important to the final result.

**Pull request merged**
