### PR TITLE
Add `--uid`, `--gid`, `--user`, `--group`

### PR DESCRIPTION
**Pull request by bennyyip**
#307

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you very much for your contribution.

I didn't have time to look at this in detail, so far. I still stand by my statement in #307, so I will first have to think about this. Thank you for your patience.

**Comment by sharkdp** [comment]
I think I'd be in favor of this if we can somehow avoid adding four new command line options. Something like what has been suggested in #307:
```
--user [<username>][:<group>]
```

which could be used as
```
--owner sharkdp
--owner sharkdp:somegroup
--owner :somegroup
```

I wouldn't care about UID/GID personally (unless there is a good reason why this is needed).

**Comment by neersighted** [comment]
Files can often be owned by a non-existent user or group (meaning only UID/GID is available). I think that using the syntax you described, but allowing numeric IDs in addition to names makes the most sense. This is basically identical to the semantics of `chown`, and very intuitive in my opinion.

**Comment by tmccombs** [comment]
> I think that using the syntax you described, but allowing numeric IDs in addition to names makes the most sense. 

that makes sense to me

**Comment by bennyyip** [comment]
I like the neat `--owner` syntax. As @neersighted , sometimes we need UID/GID.
So I think `<username>` should be parsed as username by default, unless it is a number, which should be parsed as a uid. Same for `<group`>, just like how find treat username and group.

**Comment by sharkdp** [comment]
Sounds good to me. Thank you all for your feedback!

**Comment by alexmaco** [comment]
To add a little to the discussion, I also implemented a similar feature for my own use (which you can see here https://github.com/sharkdp/fd/compare/master...alexmaco:find_by_owner).

Although i initially though that `--owner` was a good idea in principle, especially since the argument can also take a group, i found that calling it `--user` still seems more natural, in the rule-of-least-astonishment way. It could be just my preference however, and owner still seems more logical. The issue with `--user` is the collision with `-u | --unrestricted`, and having to use `-U` for the short form, which seems a little ugly, whereas `-o` was available for owner.

Second, I found that negation was easy to implement and surprisingly useful in my personal use cases, mostly as a "files not owned by me", or "files not owned by root" kind of way.

Lastly, what was surprisingly difficult to write in a simple and easy to parse manner was the help text for the `[ [!] <uid|username> ] [ : [!] <gid|groupname> ]` grammar. I still don't think i have it concise enough.

To be clear, I'm just sharing a few impressions (also from a users perspective), but this is not intended to be read as pressure for adding this feature to master (it's enough for me to update my fork sometimes). Hopefully these are useful in some way.

**Comment by sharkdp** [comment]
@alexmaco Thank you for the feedback. One thing I noticed while looking through your changes is the now-obligatory call to `fs::metadata` (even when no filtering for the user is present). Note that this is an additional syscall (`lstat`) on Unix platforms which incurs some measureable overhead.

**Comment by sharkdp** [comment]
Closing this as #581 has been merged. @bennyyip Thank you very much for your initial work on this. Everyone else: thank you for the discussion.

**Pull request closed without merging**
