### PR TITLE
fix: display color when `NO_COLOR` is an empty string

### PR DESCRIPTION
**Pull request by acuteenvy**
Same as https://github.com/sharkdp/bat/pull/2767.

### CODE REVIEW

**Review by tavianator — APPROVED** [review]

**Comment by tavianator** [comment]
Hmm I just realized after merging this that we should add a test.  Do you feel like doing that @acuteenvy?

**Comment by acuteenvy** [comment]
I can't seem to get `fd` to output color in tests at all, unless I pass `--color=always` which makes the test pointless.

**Comment by tmccombs** [comment]
It would be possible to write a test, at least on linux. But it would working with a pty, which would be fairly involved.

**Comment by tavianator** [comment]
Right yeah, I don't think it's worth the effort

**Pull request merged**
