### PR TITLE
Add snapcraft support

### PR DESCRIPTION
**Pull request by popey**
I created a snap package of fd so it can be featured to the millions of Linux users installing apps from the [Snap Store](https://snapcraft.io/store). If you're willing to publish this under the fd project name, you just need to [create an account](https://snapcraft.io/snaps) and then [register the fd name](https://snapcraft.io/register-snap).

The snap file created by snapcraft can then be released in the Snap Store with snap push --release stable *.snap. You'll want to install snapcraft (brew install snapcraft, snap install snapcraft, or apt install snapcraft) and login (snapcraft login) first, though.

Once in the snap store, you’ll need to [request classic confinement](https://forum.snapcraft.io/t/process-for-reviewing-classic-confinement-snaps/1460) with a [forum post](https://forum.snapcraft.io/), because fd will need to be unconfined (via classic confinement) so it has access to the entire filesystem.

You may also want to consider using [https://build.snapcraft.io/](https://build.snapcraft.io/) which is a free build service, that can create armhf, amd64, i386, arm64 and other builds of fd, and push them to the store automatically.

Thanks for making fd! :)

### CODE REVIEW

**Comment by popey** [comment]
Great questions. If you use something like build.snapcraft.io or travis, you'll get per-commit or daily updates in the `edge` channel in the store with no additional work from you. When you do stable releases, you can "snapcraft release fd (releaseno) stable" and that will point the `stable` channel at that revision. It's possible to push beta releases to the `beta` channel so adventurous users and committed community people can test it. But that's up to you.

Essentially there's not a huge amount of maintenance in keeping the snap up to date, for such a simple snap. You might get a relatively significant influx of users though, as people discover the application and as we promote it (we love promoting great apps on our social channels). 

I'm happy to help if you get stuck or need help in the future.

**Comment by sharkdp** [comment]
Thank you for the clarifications. I will try it out :+1: (might take me a few days until I get to it)

Minor detail: does the `snapcraft.yaml` file need to be in a specific folder (`snap/` in the root of the repo) or can it be moved to a subfolder?

**Comment by sharkdp** [comment]
When trying to register the name, I get:
> The snap name "fd" is reserved.

**Comment by popey** [comment]
@sharkdp Apologies for the delay getting back to you.
The `snapcraft.yaml` can be `/snap/snapcraft.yaml`, `/snapcraft.yaml` or `/.snapcraft.yaml`.
When you attempted to register fd, it should have offered you the option of disputing the name. Follow that procedure, and someone on the store team will check to see if it was registered by someone else, or reserved for some other reason.

**Comment by sharkdp** [comment]
> When you attempted to register fd, it should have offered you the option of disputing the name.

I do not get any message conerning the name disputal:

image

Maybe it is because `fd` is too short and everything shorter than three letters is blocked?

**Comment by popey** [comment]
I'm very sorry. You've uncovered a [bug](https://github.com/canonical-websites/snapcraft.io/issues/852) in our storefront.  Please go to https://dashboard.snapcraft.io/register-snap/?name=fd and click "Request reserved name"

**Comment by sharkdp** [comment]
Oh, no worries. Thank you for the link. I requested a review for the `fd` name.

**Comment by tmccombs** [comment]
> Maybe it is because fd is too short and everything shorter than three letters is blocked?

**Comment by popey** [comment]
I have approved the use of the 'fd' name in the snap store. It's now yours.

**Comment by sharkdp** [comment]
> I have approved the use of the 'fd' name in the snap store. It's now yours.

Great, thank you!

**Comment by pablopunk** [comment]
@sharkdp I still can't find the snap, did u release it yet on snapcraft?

https://snapcraft.io/fd

**Pull request merged**
