### PR TITLE
feat: Add a way to escape { in exec templates.

### LINKED ISSUE #1303: Exec: Allow literal placeholder {}
Sometimes a literal {} is needed that doesn't get parsed as placeholder. 

## Use-case

I wanted to refactor my go code where `interface{}` can be now written as `any`. I therefore wanted to search-replace all occurences using `fd` and `sed`. I couldn't find a way telling `fd` to not interpret the `{}` as placeholder.

### Reproducer

```go
fd -e go -X echo "interface{}"
```

Within my folder with only a `hello.go` file, this just outputs: `interface./hello.go`

My goal would be: `interface{} hello.go`

## Proposed Solution

Allowing `{{}}` which gets detected as something like `LITERAL` and gets replaced with `{}` should work.

### PR DESCRIPTION
**Pull request by tmccombs**
fixes #1303

### CODE REVIEW

**Comment by tavianator** [comment]
I think doing it [like Rust](https://doc.rust-lang.org/std/fmt/index.html#escaping) (`{{` -> `{`, `}}` -> `}`) would be nice, but maybe that's too much of a compatibility hazard?

**Comment by tmccombs** [comment]
I briefly considered that, but maybe it deserves more thought. "{{" would be pretty simple to do. "}}" is a little more difficult, I can't just add it to the regex because then something like  "{}}" would match the "{}" before the "}}". A lookahead rule would fix that, but the regex crate doesn't support lookaheads.

I can think of a few ways to implement it:
1. Support "}}" but only if it doesn't overlap with one of the other patterns
2. Roll our own state machine to find the patterns instead of using regex
3. Have the regex match `[^}]|$` at the end, and have some logic to exclude that somehow (including backtracking the search one character unless it is at the end).

Of those I think I prefer 2.

**Comment by tavianator** [comment]
I think you can do it with a regex by taking advantage of preference order.  `{{|}}|{}` will match the escaped `{{` or `}}` preferentially before it will match a `{}`.

**Comment by tmccombs** [comment]
No: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=9a2ea3ddff0596894ff5439d899463b4

I think it matches "{}" at the current position, so it doesn't try matching at the next character.

**Comment by tavianator** [comment]
Oh I see.  It would work for Rust because `{}}` is a syntax error, every brace needs to be either escaped or part of a `{}` substitution.

**Comment by sharkdp** [comment]
Let's close this in favor of #1318?

**Pull request closed without merging**
