### PR TITLE
Change full path tests to be more resilient

### PR DESCRIPTION
**Pull request by tmccombs**
Use patterns that won't conflict with randomly generated portion of temporary directory

Fixes: #1181

### CODE REVIEW

**Comment by tavianator** [comment]
Maybe the failing Windows tests are due to `/` vs `\`?

**Comment by tmccombs** [comment]
Yeah, they are. I didn't think about that :(

**Comment by sharkdp** [comment]
Thank you! Does this completely solve #1181 though? Don't we have other full-path tests that could suffer from this issue?

**Comment by tmccombs** [comment]
I looked through the other full-path tests and didn't see any others that would run into this problem. 

Specifically:

- test_full_path_glob_searches: the pattern includes "/one/", so it will only match if it is in a directory named exactly "one", which the tempdir should not be.
- test_full_path would have to match "three.*foo", and since "threefoo" is 7 characters long, it is impossible for the current implementation to generate a temporary directory that includes that in the random sequence (it only uses 6 ascii characters right now). Although I suppose that is an implementation detail and might change in the future if we don't explicitly specify how many random chars to use. We could probably do something similar here. 

However, I did realize, that it might be possible for the base temporary directory (as returned by `std::env::temp_dir()`) to be a subdirectory of the user's home directory (or really any directory, depending on environment variables).  That would be more difficult to deal with, because we have no control over that (when users run tests themselves), the best we can do is make the patterns unlikely to match.  That shouldn't impact CI though.

**Comment by sharkdp** [comment]
Thank you for the explanation!

> However, I did realize, that it might be possible for the base temporary directory (as returned by `std::env::temp_dir()`) to be a subdirectory of the user's home directory (or really any directory, depending on environment variables). That would be more difficult to deal with, because we have no control over that (when users run tests themselves), the best we can do is make the patterns unlikely to match. That shouldn't impact CI though.

Ok. Let's postpone this for now :smile:

**Pull request merged**
