### PR TITLE
Add --no-extension flag

### LINKED ISSUE #673: Can not find file without extension
**Describe the bug you encountered:**

Though the folder has few files without extension, but the following command returns nothing.

`$ fd -t f -e ''`

**Describe what you expected to happen:**

I expected to have a output ~similar to the output of `find . -type f ! -name "*.*"`

**What version of `fd` are you using?**
fd 8.1.1

**Which operating system / distribution are you on?**
Linux 5.4.0-52-generic x86_64
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 20
Release:	20
Codename:	ulyana

### PR DESCRIPTION
**Pull request by jacobmischka**
Add shorthand flag to only show results with no file extension (including directories and other commonly extensionless files).

Fixes #673

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you very much for your contribution!

I'd rather not add a new option for this niche use case (see `fd` goals in README: "While it does not seek to mirror all of find's powerful functionality, it provides sensible (opinionated) defaults for 80% of the use cases.").

I'd be great to update the `--help` text, though (similar to what I wrote in #673)

**Comment by mailsanchu** [comment]
Is this --no-extension removed? I am getting an error when I use

**Comment by tavianator** [comment]
@mailsanchu `--no-extension` was never added I think.  But https://github.com/sharkdp/fd/issues/673#issuecomment-715914285 gives some examples for how to achieve the same thing.

**Comment by mailsanchu** [comment]
Thank you very much. Actually I want to delete all files with an extension. How we can achieve it using fd
Using find we can do this 
find "$PWD" -type f -not -name "*.*" -exec rm -rvf {} \;

**Comment by tavianator** [comment]
> Actually I want to delete all files with an extension

Do you mean *without* an extension?

Your `find` command should use `-not -name '*.*'` I think, otherwise it will delete everything not named `.`.  (And `rm -r` isn't needed with `-type f`.)

For `fd`,

```
fd '^[^.]*$' --type f
```

will match all files without extensions, so

```
fd '^[^.]*$' --type f -X rm -vf
```

will delete them.

**Comment by mailsanchu** [comment]
Do you mean without an extension?
No I mean files with extension ( wit dot in the file name)

**Comment by mailsanchu** [comment]
I think I found a way to do it 
` fd '[.]' --type f -d1`

**Pull request closed without merging**
