### PR TITLE
Adding aarch64-apple-darwin target

### PR DESCRIPTION
**Pull request by yhakbar**
Adds build target for Apple M1 chips.

### CODE REVIEW

**Comment by sharkdp** [comment]
The build currently breaks. I think this would require us to set up cross compilation?

Note: The whole CI system will be moved to GitHub actions soon (with cross compilation already included), so it might make more sense to wait until that has been done.

**Comment by yhakbar** [comment]
Sounds good @sharkdp . Would you prefer that I close this PR or leave it up for tracking purposes as the project moves to GHA?

**Comment by sharkdp** [comment]
Let's leave it open for now. Thank you :+1:

**Comment by sharkdp** [comment]
The project has now been migrated to GHA. Maybe you could re-attempt to create this PR?

**Pull request closed without merging**
