### PR TITLE
Show stderr on exec with `rm -i` like `find`

### PR DESCRIPTION
**Pull request by spk**
Hi this fix issue reported in https://github.com/sharkdp/fd/issues/178, cheers

### CODE REVIEW

**Comment by sharkdp** [comment]
Welcome and thank you very much for your contribution!

I somehow don't like that we have to special-case the tests for Travis CI. Could we write a simpler test without using `rm`? We would somehow need a simple program that writes a well-defined message to stderr.

**Comment by iology** [comment]
This patch just solves part of the problem. What if (with another program) the info is printed to stdout?

**Comment by spk** [comment]
Thanks, I made a fix in https://github.com/sharkdp/fd/pull/186/commits/85f9c7f28fc4618331647801b8a51b9671fb07fa (hopefully CI will be green)
I don't know other use case with stdin and asking an input since `read` redirect output to stderr also
Cheers

**Comment by reima** [comment]
This change side steps the issue by printing stderr directly to the console. This will intersperse the outputs from different command invocations instead of keeping the output of each single invocation together like before. (stdin is still captured and only printed after the command exits.)

Another solution was already proposed in #178 by ChengCat: close the command's stdin, so it can never block on input from stdin. I'll create a PR with this change shortly.

**Comment by sharkdp** [comment]
@spk Due to the points raised by @reima, I'm going to close this in favor of #193. Nevertheless, thank you very much for your contribution!

**Pull request closed without merging**
